fullname: "Jeff Solomon"
name: "Jeff"
description: "Heyo"

url: "http://0.0.0.0:4000"

paginate: 10

markdown: kramdown
markdown_ext: md
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "tables"]
kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  input: GFM
permalink: pretty
highlighter: rouge
gems: [jekyll-last-modified-at, jekyll-paginate]
