version: '3'

services:
  jekyll:
    image: jekyll/jekyll:latest
    environment:
      - JEKYLL_UID=1000
      - JEKYLL_GID=1000
      - JEKYLL_DEBUG=""
      - VERBOSE=""
      - FORCE_POLLING=""
    volumes:
      - .:/site/
    ports:
      - "4000:4000"
    command: jekyll serve -s /site/ --watch
